permalink: /:year/:month/:day/:title
plugins:
  - jekyll-paginate
  - jekyll-feed
paginate: 5
paginate_path: "/notes/:num/"
include: [".well-known"]
navigation:
  - text: Home
    url: /
    tooltip: <img alt="me" class="icon" height="60" src="/images/me-small.png" width="72"> About me.
  - text: Field Notes
    url: /notes/
    tooltip:  <img alt="carpeliam" class="icon" height="40" src="/images/carpeliam-small.png" width="124"> Blog.
  # - text: Portfolio
  #   url: /portfolio.html
  #   tooltip: '<img alt="Portfolio-small" height="50" src="/images/portfolio-small.png" style="vertical-align: middle; border: 1px solid black" width="50"> Portfolio'
  - text: For Hire
    url: /for-hire
    tooltip: <img alt="LinkedIn" class="icon" height="60" src="/images/linked_in.png" width="60"> Currently available for hire.
  - text: Contact
    url: mailto:%6c%69%61%6d@%63%61%72%70%65%6c%69%61%6d.%63%6f%6d?subject=I%20saw%20you%20on%20the%20internet
    tooltip: ðŸ“¬ Let's get in touch.
